@url=http://localhost:8001/api/says
### get says
get {{url}}

### post
post {{url}}/new
Content-Type: application/json

{
    "author": "yiny1111",
    "content": "test"
}

### put modify
put {{url}}/modify/1
Content-Type: application/json

{
    "author": "innei",
    "content": "t22"
}

### info 
get {{url}}/info