@url=http://localhost:8001/api/says
@host=http://localhost:8001/

### get says
get {{url}}

### post
post {{url}}/new
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGE1ZWVlYmMyMmI2NTkxNzc0NjNlNSIsImlhdCI6MTU2NTI3MDA5OX0.ViANElBY5JlEioB0D4Edu0hTpfpblCktvjjBC1ULjCo

{
    "author": "yiny",
    "content": "学习本身是枯燥的，但如果变成你要学，而不是要你学，那就变成了一件非常快乐的事情。"
}

### put modify
put {{url}}/modify/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGE1ZWVlYmMyMmI2NTkxNzc0NjNlNSIsImlhdCI6MTU2NTI3MDA5OX0.ViANElBY5JlEioB0D4Edu0hTpfpblCktvjjBC1ULjCo
Content-Type: application/json

{
    "author": "Innei",
    "content": "t22"
}

### info 
get {{url}}/info

### install user create
post {{host}}install
Content-Type: application/json

{
    "username": "test",
    "password": "t"
}

### login api
post {{host}}api/login
Content-Type: application/json

{
    "username": "test",
    "password": "1"
}

### configs post
post {{host}}api/info/query/test2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGE1ZWVlYmMyMmI2NTkxNzc0NjNlNSIsImlhdCI6MTU2NTI3MDA5OX0.ViANElBY5JlEioB0D4Edu0hTpfpblCktvjjBC1ULjCo

{
    "value": "2"
}

### get all configs
get {{host}}api/info/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkNGE1ZWVlYmMyMmI2NTkxNzc0NjNlNSIsImlhdCI6MTU2NTI3MDA5OX0.ViANElBY5JlEioB0D4Edu0hTpfpblCktvjjBC1ULjCo
